config/routes.rb
Rails.application.routes.draw do
  
  
  resources :lists do
    resources :tasks, shallow: true
  end
  
  get '/add-list-tasks-logs' => 'lists#add_list_tasks_logs' 
  post '/add-list' => 'lists#add_list', as: 'add_list'

  root 'home#index'
  get '/move-task/:id' => 'tasks#move' , as: 'move-task'
  patch '/move-task-change' => 'tasks#move_task'
  get '/show-list-not-active' => 'lists#show_list_not_active'
  get '/show-task-not-active' => 'tasks#show_task_not_active'

  get '/change-lang/:locale' => 'profiles#change_lang'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :tasks, -> {where hidden: true}, dependent: :destroy, autosave: true
	default_scope { where(hidden: true) }
	accepts_nested_attributes_for :tasks#, :allow_destroy => true
	validates :name,
		presence: true,
		length: {minimum: 5}

	def format_name_list
		"##{id} - #{name}"
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :new_list,  only: [:new, :index, :add_list_tasks_logs]
  before_action :list_nested_params, only:[:add_list]

  # GET /lists
  # GET /lists.json
  def index
    
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url}
        #format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    p "++++++++++++++++++++++++++++++====++++++++++++="
    p params
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url}
        #format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    redirect_to root_url
  end

  def show_list_not_active
    @lists = List.all.unscoped.where(hidden:false)
  end

  def add_list_tasks_logs
    (0..2).each do |x|
      t = @list.tasks.build
      t.logs.build(action_name:"Create", date_update: Time.now)
    end
  end

  def add_list
    list = List.new(list_nested_params)
    list.save
    redirect_to root_url
  end

  private
    def new_list
      @list = List.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.unscoped.find_by(id:params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :hidden)
    end

    def list_nested_params
      params.require(:list).permit(:name, :hidden ,{tasks_attributes:[:name, :description, :hidden, logs_attributes:[:action_name, :date_update]]})
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
- if @list.nil?
  %h2 List not found
- else
  = form_for @list,:html => { class: "form-horizontal"} do |f|
    - if @list.errors.any?
      #error_explanation
        %h2
          = pluralize(@list.errors.count, "error")
          prohibited this list from being saved:
        %ul
          - @list.errors.full_messages.each do |message|
            %li= message
    .col-sm-6.col-sm-offset-3
      .panel.panel-primary
        .panel-heading
          .row
            .col-xs-7.col-sm-10.col-md-7
              %h3.panel-title List
        .panel-body
          .form-group
            %label.col-sm-2.control-label{:for => "txtNameList"} Name
            .col-sm-10
              = f.text_field :name , class: "form-control"
          .form-group
            %label.col-sm-2.control-label{:for => "txtNameList"} Hidden
            .col-sm-10
              = f.check_box :hidden , {class: "form-control" }, "1", "0"
        .panel-footer
          = f.submit class: "btn btn-primary"
      .panel.panel-primary
        .panel-heading
          .row
            .col-xs-7.col-sm-10.col-md-7
              %h3.panel-title Detail list
        .panel-body
          %table#tbList.table.table-hover
            %thead
              %tr
                %th ID Task
                %th Task Name
                %th Des
                %th Action
            %tbody
              - @list.tasks.each do |task|
                %tr
                  %td= task.id
                  %td= task.name
                  %td= task.description
                  %td
                    .btn-group.btn-group-xs.pull-right.button.Lists{"aria-label" => "Extra-small button group", :role => "group"}
                      = link_to "/move-task/#{task.id}", class: "btn btn-primary btn-xs" do
                        %span.glyphicon.glyphicon-move
                      = link_to edit_task_path(task), class: "btn btn-primary btn-xs" do
                        %span.glyphicon.glyphicon-pencil
                      = link_to task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" do
                        %span.glyphicon.glyphicon-remove-circle
= @para

app/views/lists/_form_log.html.haml
.form-group
  %label.col-sm-2.control-label Action name:
  .col-sm-10
    = log.text_field :action_name, class: "form-control"
.form-group
  %label.col-sm-2.control-label Date update
  .col-sm-10
    = log.date_field :date_update , class: "form-control"

app/views/lists/_form_tasks.html.haml
.form-group
  %label.col-sm-2.control-label Name
  .col-sm-10
    = task.text_field :name , class: "form-control"
.form-group
  %label.col-sm-2.control-label Description
  .col-sm-10
    = task.text_area :description , class: "form-control"
.form-group
  %label.col-sm-2.control-label Hidden
  .col-sm-10
    = task.check_box :hidden , {class: "form-control" }, "1", "0"
= task.fields_for :logs do |l|
  .panel.panel-primary
    .panel-heading
      .row
        .col-xs-7.col-sm-10.col-md-7
          %h3.panel-title Log
    .panel-body
      = render 'form_log', log:l

app/views/lists/add_list_tasks_logs.html.haml
= form_for @list, url: add_list_path ,:html => { class: "form-horizontal"} do |f|
  .col-sm-6.col-sm-offset-3
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-7.col-sm-10.col-md-7
            %h3.panel-title List
      .panel-body
        .form-group
          %label.col-sm-2.control-label Name
          .col-sm-10
            = f.text_field :name , class: "form-control"
        .form-group
          %label.col-sm-2.control-label Hidden
          .col-sm-10
            = f.check_box :hidden , {class: "form-control" }, "1", "0"
        = f.fields_for :tasks do |t|
          .panel.panel-primary
            .panel-heading
              .row
                .col-xs-7.col-sm-10.col-md-7
                  %h3.panel-title Task
            .panel-body
              = render 'form_tasks', task: t
      .panel-footer
        = f.submit class: "btn btn-primary"

app/views/lists/edit.html.haml
%h1 Editing List
= render 'form'

app/views/lists/index.html.haml
%p#notice= notice
%h1 Listing Lists
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @lists.each do |list|
      %tr
        %td= list.name
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/lists/new.html.haml
%h1 New List
= render 'form'
= t '.title'

app/views/lists/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @list.name

app/views/lists/show_list_not_active.html.haml
.col-sm-6.col-sm-offset-3
  .panel.panel-primary
    .panel-heading
      .row
        .col-xs-7.col-sm-10.col-md-7
          %h3.panel-title List hidden
    .panel-body
      %table#tbList.table.table-hover
        %thead
          %tr
            %th List id
            %th List name
            %th Action
        %tbody
          - @lists.each do |list|
            %tr
              %td= list.id
              %td= list.name
              %td
                .btn-group.btn-group-xs.pull-right.button.Lists{"aria-label" => "Extra-small button group", :role => "group"}
                  = link_to edit_list_path(list), class: "btn btn-primary btn-xs" do
                    %span.glyphicon.glyphicon-pencil
                  = link_to list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" do
                    %span.glyphicon.glyphicon-remove-circle