config/routes.rb
Rails.application.routes.draw do
  
  
  resources :lists do
    resources :tasks, shallow: true
  end
  
  get '/add-list-tasks-logs' => 'lists#add_list_tasks_logs' 
  post '/add-list' => 'lists#add_list', as: 'add_list'

  root 'home#index'
  get '/move-task/:id' => 'tasks#move' , as: 'move-task'
  patch '/move-task-change' => 'tasks#move_task'
  get '/show-list-not-active' => 'lists#show_list_not_active'
  get '/show-task-not-active' => 'tasks#show_task_not_active'

  get '/change-lang/:locale' => 'profiles#change_lang'

end

app/views/layouts/_js_locales_info.html.haml
:javascript
  I18n.defaultLocale = "#{I18n.default_locale}";
  I18n.locale = "#{I18n.locale}";
  I18n.currentLocale();

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Jquery
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{:role => "document"}
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Bootstrap theme",{:controller => :home, :action => :index},{class: "navbar-brand"}
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to "Home", root_url
            %li= link_to "#{t('add-list')}", new_list_path
            %li= link_to "Show list hidden", show_list_not_active_path
            %li= link_to "Show task hidden", show_task_not_active_path
        / /.nav-collapse
    .container.theme-showcase{:role => "main"}
      .row
        .body
          = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = render 'layouts/js_locales_info'